"use client";
import { useEffect, useState } from "react";
import { arcadeAudio, type AudioSettings } from "../lib/audio";
import {Dialog} from "./Dialog";

export function MusicCredit(){return <small className="music-credit">Music by <a href="https://whitebataudio.com" target="_blank" rel="noreferrer">Karl Casey @ White Bat Audio</a> — Last Stop</small>;}
export function ArcadeAmbience({onSound}:{onSound:(enabled:boolean)=>void}) {
  const [settings,setSettings]=useState<AudioSettings|null>(null),[controls,setControls]=useState(false),[status,setStatus]=useState("muted"),[testStatus,setTestStatus]=useState("");
  useEffect(()=>{
    const update=()=>{setSettings({...arcadeAudio.settings});setStatus(arcadeAudio.status());onSound(arcadeAudio.settings.enabled);};arcadeAudio.load();update();
    const gesture=()=>{void arcadeAudio.activate();};
    const click=(event:MouseEvent)=>{if((event.target as HTMLElement).closest("button"))arcadeAudio.play("button");};
    const visibility=()=>{document.documentElement.dataset.tabHidden=String(document.hidden);if(document.hidden)arcadeAudio.hidden();else void arcadeAudio.activate();};
    window.addEventListener("pongit:audio",update);window.addEventListener("pointerdown",gesture);window.addEventListener("keydown",gesture);window.addEventListener("click",click);document.addEventListener("visibilitychange",visibility);
    return()=>{arcadeAudio.hidden();window.removeEventListener("pongit:audio",update);window.removeEventListener("pointerdown",gesture);window.removeEventListener("keydown",gesture);window.removeEventListener("click",click);document.removeEventListener("visibilitychange",visibility);};
  },[]);
  function enter(enabled:boolean){arcadeAudio.configure({entered:true,enabled});void arcadeAudio.activate();}
  return <><div className="arcade-background" data-effects={settings?.background!==false} data-intensity={settings?.intensity||"full"} aria-hidden="true"><div className="arcade-room"><div className="room-cabinet cabinet-left"/><div className="room-cabinet cabinet-right"/></div><div className="arcade-horizon"/><div className="arcade-grid"/></div>
    <button className="arcade-settings-toggle" aria-label="Arcade settings" title="Music, effects and background settings" disabled={!settings} aria-expanded={controls} onClick={()=>setControls(!controls)}>{status==="enabled"?"Sound on":status==="muted"?"Sound off":`Sound ${status}`} ♫</button>
    {controls && settings && <Dialog label="Arcade settings" onClose={()=>setControls(false)} className="arcade-settings side-card"><button className="modal-close" aria-label="Close arcade settings" onClick={()=>setControls(false)}>×</button><p className="eyebrow">TUNE YOUR CABINET</p><h2>Your sound.</h2><p role="status">Audio {status}. {status==="suspended" && "Use Test sound to resume."}</p><button aria-pressed={settings.enabled} onClick={()=>{arcadeAudio.configure({enabled:!settings.enabled,entered:true});void arcadeAudio.activate();}}>Sound {settings.enabled?"on":"off"}</button><label>Music · {Math.round(settings.music*100)}%<input aria-label="Music volume" type="range" min="0" max="100" value={settings.music*100} onChange={e=>arcadeAudio.configure({music:Number(e.target.value)/100})}/></label><label>Effects · {Math.round(settings.effects*100)}%<input aria-label="Effects volume" type="range" min="0" max="100" value={settings.effects*100} onChange={e=>arcadeAudio.configure({effects:Number(e.target.value)/100})}/></label><button onClick={()=>{arcadeAudio.configure({enabled:true,entered:true});void arcadeAudio.test().then(()=>{setTimeout(()=>{const d=arcadeAudio.diagnostics();setTestStatus(d.peak>.0001?"Signal generated. If you hear nothing, check this tab and your output device.":"No measurable output. Check the effects volume and try again.");},40);});}}>Test sound</button><p role="status">{testStatus}</p><details><summary>Room appearance</summary><button aria-pressed={settings.background} onClick={()=>arcadeAudio.configure({background:!settings.background})}>Background effects {settings.background?"on":"off"}</button><label>Background intensity<select aria-label="Background intensity" value={settings.intensity} onChange={e=>arcadeAudio.configure({intensity:e.target.value as "subtle"|"full"})}><option value="subtle">Subtle</option><option value="full">Full arcade</option></select></label><small>The room stays still. Reduced motion follows your device setting.</small></details><MusicCredit/></Dialog>}
    {settings && !settings.entered && <Dialog label="Enter PONGIT arcade" onClose={()=>enter(false)} backdropClass="arcade-entry" className="entry-cabinet"><p className="eyebrow">WELCOME TO THE NIGHT SHIFT</p><h2>THE ARCADE<br/>IS OPEN.</h2><p>Pick a rival. Chase seven points.<br/>Stay for one more game.</p><button className="primary" data-autofocus onClick={()=>enter(true)}>Enter arcade ♫</button><button onClick={()=>enter(false)}>Enter muted</button><MusicCredit/></Dialog>}
  </>;
}
