"use client";
import {useEffect,useRef,useState} from 'react';
import {isAddress,type Address} from 'viem';
import type {IndependentManifest} from '../../shared/independent';
import {independentReader} from '../../shared/independent-read';
import {independentBase} from '../lib/independent';
import {saveIndependentPrivate,unlockIndependentPrivate,discardIndependentUpload} from '../lib/independent-private';
import {IconButton} from './IconButton';

export function IndependentPrivate({manifest,player,kind,onChallenge,matchRef,atUs=0n}:{manifest:IndependentManifest;player:Address;kind:'contacts'|'notebook';onChallenge?:(p:Address)=>void;matchRef?:string;atUs?:bigint}){
 const key=useRef<CryptoKey|null>(null),generation=useRef(0),working=useRef(false);
 const [data,setData]=useState<any>(null),[revision,setRevision]=useState(0n),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[target,setTarget]=useState(''),[nickname,setNickname]=useState(''),[note,setNote]=useState(''),[conflict,setConflict]=useState(false);
 const clear=()=>{generation.current++;key.current=null;setData(null);setTarget('');setNickname('');setNote('');setMessage('');setRevision(0n);setConflict(false);};
 useEffect(()=>{clear();return()=>{generation.current++;key.current=null;};},[player,kind]);
 async function run(fn:(g:number)=>Promise<void>){if(working.current)return;working.current=true;setBusy(true);setMessage('');try{await fn(generation.current);}catch(e){setMessage((e as Error).message);}finally{working.current=false;setBusy(false);}}
 async function unlock(g:number){const opened=await unlockIndependentPrivate(manifest,player,kind);if(g!==generation.current)return;key.current=opened.key;setData(opened.data);setRevision(opened.revision);setConflict(!!opened.conflict);setMessage(opened.conflict?'Another backup was committed. The saved copy is loaded; your pending encrypted upload is kept until you discard it.':opened.resumable?'Unfinished encrypted save recovered. Save encrypted to resume.':opened.imported?'Your previous data is loaded. Save encrypted to migrate this copy to Monad.':'Unlocked in memory.');}
 async function save(g:number){if(!data||!key.current)return;const next=await saveIndependentPrivate(manifest,player,kind,key.current,data,revision,(done,total)=>{if(g===generation.current)setMessage(`Saving encrypted chunks ${done} / ${total}`);});if(g!==generation.current)return;setRevision(next);setMessage('Encrypted copy saved on Monad.');}
 async function address(){if(isAddress(target))return target;const r=independentReader(independentBase(),manifest);const found=await r.profiles('handleOwner',[await r.profiles('handleKey',[target.trim()])]);if(/^0x0{40}$/.test(found))throw Error('Username not found');return found as Address;}
 return <section className="notebook"><h3>{kind==='contacts'?'Private contacts':'Private notebook'}</h3>{!data?<><p>Only your passkey can decrypt this list. Ciphertext is stored on Monad.</p><button disabled={busy} onClick={()=>void run(unlock)}>Unlock {kind==='contacts'?'contacts':'notebook'} ↗</button></>:<>
  <div className="rooms-button-row"><button disabled={busy||conflict} onClick={()=>void run(save)}>Save encrypted</button><button onClick={clear}>Lock</button><button disabled={busy} onClick={()=>void run(unlock)}>Reload saved copy</button>{conflict&&<button disabled={busy} onClick={()=>{discardIndependentUpload(manifest,player,kind);setConflict(false);setMessage('Pending encrypted upload discarded. The saved copy is unchanged.');}}>Discard pending upload</button>}</div>
  <label>Username or address<input value={target} onChange={e=>setTarget(e.target.value)} autoComplete="off"/></label>{kind==='notebook'&&<label>Private nickname<input value={nickname} maxLength={40} onChange={e=>setNickname(e.target.value)}/></label>}
  <button disabled={busy||!target.trim()} onClick={()=>void run(async g=>{const p=await address();if(g!==generation.current)return;if(kind==='contacts')setData({...data,contacts:[...data.contacts.filter((c:any)=>c.address.toLowerCase()!==p.toLowerCase()),{address:p,addedAt:Date.now()}]});else setData({...data,rivals:[...data.rivals.filter((c:any)=>c.address.toLowerCase()!==p.toLowerCase()),{address:p,nickname,note:''}]});setTarget('');setNickname('');})}>Add {kind==='contacts'?'contact':'rival'}</button>
  {(kind==='contacts'?data.contacts:data.rivals).map((c:any)=><div className="notebook-row" key={c.address}><span>{c.nickname||c.address}</span>{onChallenge&&<button onClick={()=>onChallenge(c.address)}>Challenge</button>}<IconButton aria-label={`Remove ${c.nickname||c.address}`} onClick={()=>setData({...data,[kind==='contacts'?'contacts':'rivals']:(kind==='contacts'?data.contacts:data.rivals).filter((x:any)=>x!==c)})}/></div>)}
  {kind==='notebook'&&<><h3>Replay notes</h3><p>{matchRef||'Open a match to attach a note.'}</p><textarea value={note} maxLength={2000} onChange={e=>setNote(e.target.value)}/><button disabled={!note.trim()||!matchRef} onClick={()=>{setData({...data,notes:[...data.notes,{id:crypto.randomUUID(),matchRef,atUs:String(atUs),text:note}]});setNote('');}}>Add note</button>{data.notes.map((n:any)=><div className="notebook-row" key={n.id}><span><small>{n.matchRef} · {Number(n.atUs)/1e6}s</small>{n.text}</span><IconButton aria-label="Remove note" onClick={()=>setData({...data,notes:data.notes.filter((x:any)=>x!==n)})}/></div>)}<label>Preferred mode<select value={data.settings.preferredMode} onChange={e=>setData({...data,settings:{...data.settings,preferredMode:Number(e.target.value)}})}><option value="0">Classic</option><option value="1">Chaos</option></select></label></>}
  <p>Unsaved edits stay in memory. Reload before merging changes from another device.</p>
 </>}{message&&<p role="status">{message}</p>}</section>;
}
