"use client";
import { useEffect, useState } from "react";
import { decodeAbiParameters, parseEther, type Address } from "viem";
import { api, relay, short, stateFromJson, type Config } from "../lib/api";
import { stateComponents as stateV2Components } from "../../shared/physics-v2";
import { stateComponents } from "../../shared/physics";
import { deploymentId, type Deployment, domain, withdrawTypes } from "../../shared/protocol";
import type { Identity } from "../lib/wallet";
import type { State } from "../../shared/physics-v2";
import { Court } from "./Court";

export function Legacy({config,account,signer,closeSigner,legacy}:{legacy:Deployment;config:Config;account:string;signer:()=>Promise<Identity>;closeSigner:()=>void}) {
  const [claims,setClaims]=useState<Record<string,string>>({}),[open,setOpen]=useState(false),[items,setItems]=useState<any[]>([]),[balance,setBalance]=useState<any>(null),[frames,setFrames]=useState<any[]>([]),[index,setIndex]=useState(0),[state,setState]=useState<State|null>(null),[id,setId]=useState(""),[message,setMessage]=useState(""),[busy,setBusy]=useState(false),[amount,setAmount]=useState("0.001");
  const version=deploymentId(legacy);
  const legacyApi=(path:string)=>api(path+(path.includes("?")?"&":"?")+`deployment=${version}`);
  useEffect(()=>{let cancelled=false;setBalance(null);setClaims({});if(open && account)void Promise.all([legacyApi(`/legacy/player/${account}`),legacyApi(`/legacy/claims/${account}`)]).then(([b,c])=>{if(!cancelled){setBalance(b);setClaims(c.claims);}}).catch(e=>{if(!cancelled)setMessage(e.message);});return()=>{cancelled=true;};},[account,open,legacy.game]);
  async function run(fn:()=>Promise<void>){if(busy)return;setBusy(true);setMessage("");try{await fn();}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
  async function history(){setOpen(true);setItems((await legacyApi("/legacy/history")).Match);}
  function show(frame:any,i:number){const [s]=decodeAbiParameters([{type:"tuple",components:(legacy.version||1)>=2?stateV2Components:stateComponents}],frame.state);setState(stateFromJson(s));setIndex(i);}
  async function replay(rawId:string){const all:any[]=[];let after="0";for(let i=0;i<100;i++){const data=await legacyApi(`/legacy/replay/${rawId}?after=${after}`);all.push(...data.Frame);if(data.Frame.length<1000)break;after=data.Frame.at(-1).version;}if(!all.length){const result=await legacyApi(`/legacy/matches/${rawId}`);if(result.match.status===4 && result.match.startBlock==="0"){setState(null);setFrames([]);setMessage("Match cancelled before play. No replay was recorded.");return;}throw new Error("Legacy replay is still indexing");}setId(rawId);setFrames(all);show(all[0],0);}
  async function withdraw(){const own=await signer();try{const info=await legacyApi(`/legacy/player/${account}`);const m={player:account as Address,recipient:account as Address,amount:parseEther(amount),nonce:BigInt(info.vaultNonce),deadline:BigInt(Math.floor(Date.now()/1000)+120)};const signature=await own.account.signTypedData({domain:domain("PONG Vault",config.chainId,legacy.vault),types:withdrawTypes,primaryType:"Withdraw",message:m});closeSigner();await relay({deployment:version,contract:"vault",functionName:"withdraw",args:[m.player,m.recipient,m.amount,m.nonce,m.deadline,signature]});setBalance(await legacyApi(`/legacy/player/${account}`));setMessage("Withdrawal confirmed. Each deployment has a separate balance.");}finally{closeSigner();}}
  return <section className="side-card legacy-panel"><p className="eyebrow">ARCHIVED DEPLOYMENT / {version.toUpperCase()}</p><h2>Keep your history.</h2><p>Results and funds remain accessible. Replays follow the shared three-game retention limit. Legacy payouts credit this vault; a signed withdrawal sends them to your wallet.</p><button disabled={busy} onClick={()=>void run(history)}>Open {version.toUpperCase()} archive & balance</button>
    {open && <><p>{version.toUpperCase()} vault balance: {balance?(Number(balance.balance)/1e18).toFixed(6):"Connect to view"} MON</p>{account&&<><label>MON to withdraw to your wallet<input value={amount} onChange={e=>setAmount(e.target.value)}/></label><button disabled={busy} onClick={()=>void run(withdraw)}>Withdraw from {version.toUpperCase()} vault ↗</button></>}
    {items.map(m=><div className="invitation" key={m.id}><p>{m.id} · {short(m.playerA)} / {short(m.playerB)}</p><div className="button-row"><button disabled={busy || m.replayAvailability==="pruned" || m.replayAvailability==="not-played"} onClick={()=>void run(()=>replay(m.rawId))}>{m.replayAvailability==="pruned"?"Replay retired":m.replayAvailability==="not-played"?"Not played":`${version.toUpperCase()} replay`}</button>{claims[m.rawId]&&<button disabled={busy || !account || m.status<3} onClick={()=>void run(async()=>{await relay({deployment:version,contract:"market",functionName:"claim",args:[m.rawId,account]});setBalance(await legacyApi(`/legacy/player/${account}`));setClaims((await legacyApi(`/legacy/claims/${account}`)).claims);setMessage("Legacy payout credited. Withdraw it to your wallet with your passkey.");})}>Claim {version.toUpperCase()} bet</button>}</div></div>)}
    {state && <><p>{version}:{id} · snapshot {index+1}/{frames.length}</p><Court state={state} clock={state.t} observedAt={Date.now()} direction={0} side={-1} replay matchId={`${version}:${id}`} controllable={false} pending={false} onStats={()=>{}}/><label>Replay timeline<input aria-label={`${version.toUpperCase()} replay timeline`} type="range" min={0} max={frames.length-1} value={index} onChange={e=>show(frames[Number(e.target.value)],Number(e.target.value))}/></label></>}
    </>}{message&&<p role="status">{message}</p>}</section>;
}
