// Generated by scripts/configure-indexer.ts from public deployment manifests.
export const independentArchiveDeployments = {
  "0xc5a6468ab50faacd1c4c27b977d5a2ae977dc7dd": {
    "apps": [
      "0x18ab50f7710e599abc4d88b5928c532f61ffb071",
      "0x3a0c55bef5682d531d8b56538b7212ee1933ff6c",
      "0x98612da5cacbd96dde0a903079aa3bab0b99e8bf"
    ],
    "rulesVersion": 14
  }
} as const;
