import {test,expect} from "@playwright/test";
import docs from "../web/lib/docs.generated.json" with {type:"json"};
const base=process.env.PONG_TEST_URL||"http://localhost:3150";
for(const viewport of [{width:360,height:640},{width:390,height:844},{width:768,height:1024},{width:1440,height:1000},{width:844,height:390},{width:720,height:450}])test(`Documentation reading and search at ${viewport.width}x${viewport.height}`,async({browser})=>{
 const context=await browser.newContext({viewport,permissions:["clipboard-read","clipboard-write"]}),page=await context.newPage(),errors:string[]=[],business:string[]=[];
 page.on("pageerror",e=>errors.push(e.message));page.on("request",r=>{if(/\/api\/|\/ws($|\?)/.test(r.url())||(new URL(r.url()).pathname==="/"&&new URL(r.url()).searchParams.has("_rsc")))business.push(r.url());});page.on("websocket",s=>business.push(s.url()));
 try{
  await page.goto(base+"/docs");await expect(page.getByRole("heading",{level:1})).toContainText("Know the arcade");await expect(page.getByRole("dialog")).toHaveCount(0);expect(await page.locator("audio,canvas").count()).toBe(0);
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:`artifacts/docs-home-${viewport.width}.png`,fullPage:true});
  if(viewport.width<=800){await page.getByRole("button",{name:"Open documentation menu"}).click();const modal=page.getByRole("dialog",{name:"Documentation menu"});await expect(modal).toBeVisible();for(let i=0;i<30;i++)await page.keyboard.press("Tab");expect(await modal.evaluate(e=>e.contains(document.activeElement))).toBe(true);await page.keyboard.press("Escape");await expect(modal).toHaveCount(0);await expect(page.getByRole("button",{name:"Open documentation menu"})).toBeFocused();}
  await page.keyboard.press("Control+k");const search=page.getByRole("dialog",{name:"Search documentation"});await expect(search).toBeVisible();await search.getByRole("combobox").fill("payout");await expect(search.getByRole("option").first()).toBeVisible();await page.keyboard.press("ArrowDown");await page.keyboard.press("ArrowUp");await page.keyboard.press("Enter");await expect(page).toHaveURL(/\/docs\/.*pay/);await expect(page.getByRole("dialog")).toHaveCount(0);
  await page.getByRole("button",{name:"Search documentation"}).click();await page.getByRole("combobox").fill("zzzx-no-such-article");await expect(page.locator(".docs-search-empty")).toContainText("No results");await page.keyboard.press("Escape");await expect(page.getByRole("button",{name:"Search documentation"})).toBeFocused();
  await page.goto(base+"/docs/technical/api#websocket-events");await expect(page.getByRole("heading",{level:2,name:/WebSocket events/})).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  await page.getByRole("button",{name:"Copy code",exact:true}).first().click();await expect(page.getByRole("button",{name:"Copied",exact:true})).toBeVisible();expect(await page.evaluate(()=>navigator.clipboard.readText())).toContain("fetch");
  await page.getByRole("link",{name:"Link to Public reads",exact:true}).click();expect(await page.evaluate(()=>navigator.clipboard.readText())).toContain("#public-reads");
  await page.goto(base+"/docs/technical/contracts");await expect(page.locator(".docs-contracts section")).toHaveCount(4);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:`artifacts/docs-contracts-${viewport.width}.png`});
  if(viewport.width<=1300){const toc=page.locator(".docs-toc-mobile");await toc.locator("summary").click();await expect(toc).toHaveAttribute("open","");await page.keyboard.press("Escape");await expect(toc).not.toHaveAttribute("open","");await expect(toc.locator("summary")).toBeFocused();}
  await page.emulateMedia({reducedMotion:"reduce"});await page.getByRole("button",{name:"Search documentation"}).click();await expect(page.getByRole("dialog")).toHaveCSS("animation-name","none");await page.keyboard.press("Escape");
  expect(business).toEqual([]);expect(errors).toEqual([]);
 }finally{await context.close();}
});
test("All documentation routes, fragments, assets, metadata and real 404 responses",async({page,request})=>{
 test.setTimeout(90000);
 for(const p of docs.pages){const response=await page.goto(`${base}/docs/${p.slug}`);expect(response?.status()).toBe(200);await expect(page.getByRole("heading",{level:1})).toHaveText(p.title);await expect(page.locator('link[rel="canonical"]')).toHaveAttribute("href",`https://pongit.xyz/docs/${p.slug}`);for(const h of p.headings)expect(await page.locator(`[id="${h.id}"]`).count(),`${p.slug}#${h.id}`).toBe(1);for(const img of await page.locator(".docs-prose img").all())expect(await img.evaluate(async e=>{await (e as HTMLImageElement).decode();return (e as HTMLImageElement).naturalWidth;})).toBeGreaterThan(0);}
 expect((await request.get(base+"/docs/not-a-real-article")).status()).toBe(404);
 const sitemap=await request.get(base+"/sitemap.xml");expect(sitemap.status()).toBe(200);expect(await sitemap.text()).toContain("/docs/technical/api");
});
test("Header Docs link remains visible and does not push Play now off small screens",async({browser})=>{
 const context=await browser.newContext({viewport:{width:360,height:640}}),page=await context.newPage();try{await page.goto(base);await page.getByRole("button",{name:"Enter muted",exact:true}).click();await expect(page.locator("header").getByRole("link",{name:"Docs ↗",exact:true})).toBeVisible();await expect(page.getByRole("button",{name:"Play now",exact:false})).toBeInViewport();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);const popupPromise=context.waitForEvent("page");await page.locator("header").getByRole("link",{name:"Docs ↗",exact:true}).click();const popup=await popupPromise;await popup.waitForURL(base+"/docs");expect(await popup.evaluate(()=>window.opener)).toBeNull();expect(page.url()).toBe(base+"/");await popup.close();}finally{await context.close();}
});
test("Search recovers after its index cannot be loaded",async({page})=>{await page.route("**/search/docs-v1.json",r=>r.fulfill({status:503,body:"temporarily unavailable"}));await page.goto(base+"/docs");await page.getByRole("button",{name:"Search documentation"}).click();await expect(page.getByRole("button",{name:"Retry search"})).toBeVisible();await page.unroute("**/search/docs-v1.json");await page.getByRole("button",{name:"Retry search"}).click();await expect(page.getByRole("option").first()).toBeVisible();});
