import {openCabinet} from "./cabinet";
import {test,expect} from "@playwright/test";
import {writeFile} from "node:fs/promises";
test("V4 automatically pays two bettors including an offline wallet, without a receiving signature",async({browser})=>{
 test.setTimeout(240000);const base=process.env.PONG_TEST_URL||"http://localhost:3004",api=process.env.PONG_TEST_API||"http://localhost:4014";
 const config=await fetch(api+"/config").then(r=>r.json());expect(config.version).toBe(4);
 const contexts=await Promise.all(Array.from({length:5},()=>browser.newContext({viewport:{width:1440,height:1000}}))),pages=await Promise.all(contexts.map(c=>c.newPage()));
 const inputStarts=new Map<string,number>(),inputSamples:any[]=[];
 const addresses:string[]=[],assertions=[0,0,0,0,0],errors:string[]=[];let match:any;
 const read=async(path:string)=>{const r=await fetch(api+path);expect(r.ok).toBeTruthy();return r.json();};
 try{
  for(let i=0;i<pages.length;i++){const p=pages[i],cdp=await contexts[i].newCDPSession(p);p.on("pageerror",e=>errors.push(e.message));p.on("response",async r=>{if(r.url().endsWith("/relay") || r.url().endsWith("/inputs"))try{if((r.request().postDataJSON().request||r.request().postDataJSON()).functionName==="submitInput"){const j=await r.json();inputStarts.set(j.id,r.request().timing().startTime);}}catch{}});p.on("websocket",socket=>socket.on("framereceived",e=>{try{const j=JSON.parse(String(e.payload)),start=inputStarts.get(j.id);if(j.type==="job"&&start&&j.status==="succeeded"){inputSamples.push({job:j.id,start,observedAt:Date.now(),latencyMs:Date.now()-start,...j.timing});inputStarts.delete(j.id);}}catch{}}));await cdp.send("WebAuthn.enable");await cdp.send("WebAuthn.addVirtualAuthenticator",{options:{protocol:"ctap2",transport:"internal",hasResidentKey:true,hasUserVerification:true,isUserVerified:true,automaticPresenceSimulation:true,hasPrf:true}});cdp.on("WebAuthn.credentialAsserted",()=>assertions[i]++);
   await p.goto(base);await p.getByRole("button",{name:"Enter muted"}).click();await p.getByRole("button",{name:"Connect passkey",exact:true}).click();const response=p.waitForResponse(r=>/\/player\/0x[\da-f]+$/i.test(r.url()));await p.getByRole("button",{name:"Create a passkey"}).click();addresses.push((await response).url().split("/").at(-1)!);await expect(p.locator(".status-line")).toContainText("Arcade session ready",{timeout:30000});
   if(i>=2){await p.getByRole("button",{name:"Get test credits"}).click();await expect(p.locator(".status-line")).toContainText("credited",{timeout:30000});}
  }
  await pages[0].getByRole("button",{name:"Find an opponent"}).click();await pages[1].getByRole("button",{name:"Find an opponent"}).click();
  for(const p of pages.slice(0,2))await expect(p.locator(".match-bar")).toContainText("IN PLAY",{timeout:45000});
  match=(await read("/matches")).matches.find((m:any)=>m.status===2&&[m.playerA,m.playerB].some((p:string)=>p.toLowerCase()===addresses[0].toLowerCase()));expect(match).toBeTruthy();
  const bets=[{index:2,side:0,shares:"0.003",win:3000000000000000n},{index:3,side:0,shares:"0.005",win:5000000000000000n},{index:4,side:1,shares:"0.004",win:0n}];const balances:any[]=[];
  for(const bet of bets){const p=pages[bet.index];await p.getByRole("button",{name:/^Live/}).click();await p.locator(`[data-match-id="${match.id}"]`).click();await p.getByLabel("Shares (1 winning share = 1 MON)").fill(bet.shares);
   for(let attempt=0;attempt<10;attempt++){const button=p.getByRole("button",{name:bet.side===0?"Back 01":"Back 02"});await expect(button).toBeEnabled({timeout:15000});await button.click();await expect.poll(async()=> (await p.locator(".status-line").innerText()).includes("Bet confirmed")||await p.getByRole("button",{name:"Dismiss error"}).count()>0,{timeout:20000}).toBe(true);if((await p.locator(".status-line").innerText()).includes("Bet confirmed"))break;await p.getByRole("button",{name:"Dismiss error"}).click();await p.waitForTimeout(700);}
   await expect(p.locator(".status-line")).toContainText("Bet confirmed");balances.push(await read(`/player/${addresses[bet.index]}`));
  }
  // Two bettors play a different match while their source-market payout is processed.
  for(const i of [2,4]){await pages[i].getByRole("button",{name:"Play",exact:true}).click();await pages[i].getByRole("button",{name:"Find an opponent"}).click();}
  for(const i of [2,4]){await expect(pages[i].locator(".match-bar")).toContainText("YOU /",{timeout:40000});await expect(pages[i].locator(".match-bar")).toContainText("IN PLAY",{timeout:40000});}
  let concurrent:any;await expect.poll(async()=>{concurrent=(await read("/matches")).matches.find((m:any)=>m.status===2&&m.id!==match.id&&[m.playerA,m.playerB].some((p:string)=>p.toLowerCase()===addresses[2].toLowerCase()));return !!concurrent;},{timeout:15000}).toBe(true);
  const beforeAssertions=[...assertions];await pages[3].goto("about:blank"); // The beneficiary leaves the application: no live page, wallet key or WebSocket.
  const loser=pages[addresses.findIndex(a=>a.toLowerCase()===match.playerB.toLowerCase())];await openCabinet(loser);await loser.getByRole("button",{name:"Concede",exact:true}).click();await expect(loser.locator(".outcome h2")).toHaveText("DEFEAT",{timeout:20000});const resultObservedAt=Date.now();
  const controls=(async()=>{for(const key of ["w","s","w","s","w","s"]){await pages[2].keyboard.down(key);await pages[2].waitForTimeout(800);await pages[2].keyboard.up(key);await pages[2].waitForTimeout(200);}})();
  const evidence=[];
  for(let i=0;i<bets.length;i++){const bet=bets[i],address=addresses[bet.index];await expect.poll(async()=>BigInt((await read(`/player/${address}`)).walletBalance),{timeout:45000}).toBe(BigInt(balances[i].walletBalance)+bet.win);await expect.poll(async()=> (await read(`/payouts/${address}`)).payments.find((p:any)=>p.sourceId===match.id&&p.kind===0)?.state,{timeout:45000}).toBe(bet.win>0n?"paid":"no_payout");const now=await read(`/player/${address}`);expect(now.balance).toBe(balances[i].balance);const payment=(await read(`/payouts/${address}`)).payments.find((p:any)=>p.sourceId===match.id&&p.kind===0);evidence.push({observedAt:new Date().toISOString(),address,winningWei:String(bet.win),walletBefore:balances[i].walletBalance,walletAfter:now.walletBalance,vaultUnchanged:now.balance,payment});}
  await controls;expect(inputSamples.length).toBeGreaterThanOrEqual(3);await expect(pages[2].getByRole("button",{name:"Dismiss error"})).toHaveCount(0);
  for(const i of [2,4])await pages[i].getByText(/^Wallet payments/).click();await expect(pages[2].locator(".payment-history")).toContainText("Paid to your wallet");await expect(pages[4].locator(".payment-history")).toContainText("No payout for this bet");
  await openCabinet(pages[4]);await pages[4].getByRole("button",{name:"Concede",exact:true}).click();await expect(pages[4].locator(".outcome h2")).toHaveText("DEFEAT",{timeout:20000});expect(assertions).toEqual(beforeAssertions);for(const p of pages)await expect(p.getByRole("button",{name:/Claim.*payout|Claim.*refund/})).toHaveCount(0);
  await pages[3].goto(base);await expect(pages[3].locator(".status-line")).toContainText("Arcade session restored",{timeout:25000});expect(assertions).toEqual(beforeAssertions);
  await pages[3].getByText(/^Wallet payments/).click();await expect(pages[3].locator(".payment-history")).toContainText("Paid to your wallet");await expect(pages[3].locator(".wallet-balance")).toContainText("0.005");await pages[3].setViewportSize({width:390,height:844});expect(await pages[3].evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await pages[3].screenshot({path:"artifacts/v4-wallet-payments-mobile.png",fullPage:true});
  const body={contract:"market",functionName:"claim",args:[match.id,addresses[2]]};const replies=await Promise.all([0,1].map(()=>fetch(api+"/relay",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)}).then(r=>r.json())));expect(replies[0].id).toBe(replies[1].id);expect(BigInt((await read(`/player/${addresses[2]}`)).walletBalance)).toBe(BigInt(balances[0].walletBalance)+bets[0].win);
  expect(errors).toEqual([]);await writeFile("artifacts/v4-browser-payments.json",JSON.stringify({base,game:config.game,matchId:match.id,addresses,payments:evidence,concurrentMatchId:concurrent.id,inputSamplesDuringSettlement:inputSamples,passkeyAssertionsBeforeResult:beforeAssertions,passkeyAssertionsAfterPayment:assertions,offlineBeneficiary:addresses[3],offlineMethod:"Beneficiary navigated away from PONGIT before the result; the application and its in-memory wallet were unloaded",resultObservedAt:new Date(resultObservedAt).toISOString(),checkedAt:new Date().toISOString(),authenticator:"Chromium virtual PRF using the real Mera SDK; no physical cross-device synchronization claim"},null,2));
 }catch(e){for(let i=0;i<pages.length;i++){console.log("Payment browser",i,await pages[i].locator(".notice,.status-line").allTextContents());await pages[i].screenshot({path:`artifacts/v4-payment-failure-${i}.png`,fullPage:true}).catch(()=>{});}throw e;}finally{await Promise.all(contexts.map(c=>c.close()));}
});
