import assert from "node:assert/strict";
import { generatePrivateKey, privateKeyToAccount } from "viem/accounts";
import { cancelQueueMessage } from "../shared/protocol";
const base=process.env.E2E_API_URL || "http://localhost:4012",origin=process.env.E2E_WEB_URL || "http://localhost:3002";
const config=await fetch(base+"/config").then(r=>r.json());assert.equal(config.chainId,31337,"Social integration test uses isolated Anvil");assert.equal(config.version,2);
function client(){const account=privateKeyToAccount(generatePrivateKey());let cookie="";return {account,async call(path:string,method="GET",body?:any,expected=account.address){const response=await fetch(base+path,{method,headers:{origin,"content-type":"application/json",cookie,"x-pongit-player":expected},body:body===undefined?undefined:JSON.stringify(body)});const set=response.headers.get("set-cookie");if(set)cookie=set.split(";")[0];return {status:response.status,data:await response.json()};}};}
const a=client(),b=client(),c=client();
async function auth(actor:ReturnType<typeof client>){const n=(await actor.call("/auth/challenge","POST",{player:actor.account.address})).data;const request={player:actor.account.address,nonce:n.nonce,signature:await actor.account.signMessage({message:n.message})};assert.equal((await actor.call("/auth/session","POST",request)).status,200);assert.equal((await actor.call("/auth/session","POST",request)).status,400);}
await Promise.all([a,b,c].map(auth));
assert.equal((await a.call("/notebook","GET",undefined,b.account.address)).status,400);
const handle="test_"+a.account.address.slice(2,12).toLowerCase();
assert.equal((await a.call("/profiles","PUT",{handle,avatar:2})).status,200);
assert.equal((await b.call("/profiles","PUT",{handle,avatar:3})).status,400);
const encrypted={revision:0,iv:"A".repeat(16),ciphertext:"B".repeat(40)};
const concurrent=await Promise.all([a.call("/notebook","PUT",encrypted),a.call("/notebook","PUT",encrypted)]);
assert.deepEqual(concurrent.map(r=>r.status).sort(),[200,409]);
assert.equal((await b.call("/notebook")).data.revision,0);
assert.equal((await a.call("/notebook")).data.revision,1);
assert.equal((await a.call("/notebook","PUT",{...encrypted,revision:1})).data.revision,2);
const target=(await a.call("/challenges","POST",{recipient:b.account.address,mode:1,ranked:false})).data;
assert.equal((await c.call(`/challenges/${target.id}`)).status,400);
assert.equal((await c.call(`/challenges/${target.id}/accept`,"POST",{})).status,400);
assert.equal((await b.call(`/challenges/${target.id}/decline`,"POST",{})).data.status,"declined");
await b.call("/blocks","POST",{player:a.account.address});
assert.equal((await a.call("/challenges","POST",{recipient:b.account.address,mode:0,ranked:true})).status,400);
await b.call("/blocks","DELETE",{player:a.account.address});
const open=(await a.call("/challenges","POST",{recipient:null,mode:1,ranked:false})).data;
const accepted=await Promise.all([b.call(`/challenges/${open.id}/accept`,"POST",{}),c.call(`/challenges/${open.id}/accept`,"POST",{})]);
assert.deepEqual(accepted.map(r=>r.status).sort(),[200,400]);
const room=(await a.call(`/queue/${a.account.address}`)).data;
assert.equal(room.mode,1);assert.equal(room.ranked,false);assert.equal(room.rules_version,2);
const expires=Math.floor(Date.now()/1000)+120,ticket=room.ticket_a;
const signature=await a.account.signMessage({message:cancelQueueMessage(a.account.address,ticket,expires,config.chainId,config.game)});
assert.equal((await a.call("/queue/cancel","POST",{player:a.account.address,ticket,expires,signature})).data.cancelled,true);
await a.call("/auth/session","DELETE");assert.equal((await a.call("/notebook")).status,400);
console.log("PASS: auth replay, unique profiles, private reads, notebook concurrency, addressed links, blocking, atomic open-link acceptance and signed cancellation.");
