// Generated by scripts/docs-build.ts from the reviewed local article catalog.
import Page0 from "./getting-started/welcome.mdx";
import Page1 from "./getting-started/first-match.mdx";
import Page2 from "./getting-started/passkeys.mdx";
import Page3 from "./playing/classic.mdx";
import Page4 from "./playing/chaos.mdx";
import Page5 from "./playing/challenges.mdx";
import Page6 from "./playing/rankings.mdx";
import Page7 from "./playing/tournaments.mdx";
import Page8 from "./playing/spectating.mdx";
import Page9 from "./playing/replays.mdx";
import Page10 from "./account/profile.mdx";
import Page11 from "./account/notebook.mdx";
import Page12 from "./account/balances.mdx";
import Page13 from "./account/settings.mdx";
import Page14 from "./betting/how-it-works.mdx";
import Page15 from "./betting/payments.mdx";
import Page16 from "./help/troubleshooting.mdx";
import Page17 from "./help/faq.mdx";
import Page18 from "./technical/architecture.mdx";
import Page19 from "./technical/physics.mdx";
import Page20 from "./technical/contracts.mdx";
import Page21 from "./technical/permissions.mdx";
import Page22 from "./technical/api.mdx";
import Page23 from "./technical/operations.mdx";
export const articles:Record<string,typeof Page0>={
  "getting-started/welcome":Page0,
  "getting-started/first-match":Page1,
  "getting-started/passkeys":Page2,
  "playing/classic":Page3,
  "playing/chaos":Page4,
  "playing/challenges":Page5,
  "playing/rankings":Page6,
  "playing/tournaments":Page7,
  "playing/spectating":Page8,
  "playing/replays":Page9,
  "account/profile":Page10,
  "account/notebook":Page11,
  "account/balances":Page12,
  "account/settings":Page13,
  "betting/how-it-works":Page14,
  "betting/payments":Page15,
  "help/troubleshooting":Page16,
  "help/faq":Page17,
  "technical/architecture":Page18,
  "technical/physics":Page19,
  "technical/contracts":Page20,
  "technical/permissions":Page21,
  "technical/api":Page22,
  "technical/operations":Page23,
};
