// Generated by scripts/configure-indexer.ts from public finance manifests.
export const chaosArchiveDeployments = {
  "0xd7602b6ae87798e0f39ea25b97f75dcc5dd0822f": {
    "app": "0x78d3341e3452d7ec1add9371de3008639eed8eb0",
    "rulesVersion": 6
  }
} as const;
