// SPDX-License-Identifier: MIT
// Generated by @interludelayer-sdk/cli. Do not edit: `interlude gen` overwrites it.
//
// Every slot below came from solc's storage layout for PongInterludeRooms, not from a hash
// written by hand. That is the difference this file makes: PongInterludeRooms keeps ordinary
// Solidity storage, and nothing in it had to be rewritten to be delegated.
//
// INTERLUDE_LAYOUT commits to the layout these numbers were read from. Insert a state variable
// above a delegated one and every slot below it shifts, at which point these constants would
// name somebody else's storage. `interlude check` recomputes the commitment and fails when the
// two disagree, so run it in CI — that check is the reason this file can be trusted.
pragma solidity ^0.8.28;

import {Delegatable} from "../../vendor/interlude/Delegatable.sol";
import {Delegated} from "../../vendor/interlude/libraries/Delegated.sol";

/// @notice The storage PongInterludeRooms hands to a node, as the compiler sees it.
/// @dev Declares no state of its own, so standing between PongInterludeRooms and Delegatable
///      moves nothing. The commitment below is what proves that stayed true.
abstract contract PongInterludeRoomsInterludeSurface is Delegatable {
    /// @dev `mapping(bytes32 => uint256) words`, at slot 0. The whole mapping is one partition.
    bytes32 internal constant WORDS_SLOT = bytes32(uint256(0));

    /// @dev keccak256 over every (variable, slot, type, mode) this file asserts.
    bytes32 internal constant INTERLUDE_LAYOUT =
        0x79a696fb75444b5eb7a6c426144e17d6946e0a236d82eb8584da517144d6bb73;

    /// @notice Hand the annotated storage over. Call once, from the constructor.
    function _registerInterludeSurface() internal {
        _registerGlobalMapping(Delegated.MapUint256Slot.wrap(WORDS_SLOT));
    }
}
