// SPDX-License-Identifier: MIT
// Generated by @interludelayer-sdk/cli. Do not edit: `interlude gen` overwrites it.
//
// Every slot below came from solc's storage layout for PongInterlude, not from a hash
// written by hand. That is the difference this file makes: PongInterlude keeps ordinary
// Solidity storage, and nothing in it had to be rewritten to be delegated.
//
// INTERLUDE_LAYOUT commits to the layout these numbers were read from. Insert a state variable
// above a delegated one and every slot below it shifts, at which point these constants would
// name somebody else's storage. `interlude check` recomputes the commitment and fails when the
// two disagree, so run it in CI — that check is the reason this file can be trusted.
pragma solidity ^0.8.28;

import {Delegatable} from "../../vendor/interlude/Delegatable.sol";
import {Delegated} from "../../vendor/interlude/libraries/Delegated.sol";

/// @notice The storage PongInterlude hands to a node, as the compiler sees it.
/// @dev Declares no state of its own, so standing between PongInterlude and Delegatable
///      moves nothing. The commitment below is what proves that stayed true.
abstract contract PongInterludeInterludeSurface is Delegatable {
    /// @dev `uint256 matchId`, at slot 0. One slot, one partition.
    bytes32 internal constant MATCH_ID_SLOT = bytes32(uint256(0));

    /// @dev `uint256 version`, at slot 1. One slot, one partition.
    bytes32 internal constant VERSION_SLOT = bytes32(uint256(1));

    /// @dev `uint256 status`, at slot 2. One slot, one partition.
    bytes32 internal constant STATUS_SLOT = bytes32(uint256(2));

    /// @dev `uint256 playerA`, at slot 3. One slot, one partition.
    bytes32 internal constant PLAYER_A_SLOT = bytes32(uint256(3));

    /// @dev `uint256 playerB`, at slot 4. One slot, one partition.
    bytes32 internal constant PLAYER_B_SLOT = bytes32(uint256(4));

    /// @dev `uint256 targetPlayer`, at slot 5. One slot, one partition.
    bytes32 internal constant TARGET_PLAYER_SLOT = bytes32(uint256(5));

    /// @dev `uint256 winner`, at slot 6. One slot, one partition.
    bytes32 internal constant WINNER_SLOT = bytes32(uint256(6));

    /// @dev `uint256 openedAt`, at slot 7. One slot, one partition.
    bytes32 internal constant OPENED_AT_SLOT = bytes32(uint256(7));

    /// @dev `uint256 startBlock`, at slot 8. One slot, one partition.
    bytes32 internal constant START_BLOCK_SLOT = bytes32(uint256(8));

    /// @dev `bytes32 seed`, at slot 9. One slot, one partition.
    bytes32 internal constant SEED_SLOT = bytes32(uint256(9));

    /// @dev `int256 ballX`, at slot 10. One slot, one partition.
    bytes32 internal constant BALL_X_SLOT = bytes32(uint256(10));

    /// @dev `int256 ballY`, at slot 11. One slot, one partition.
    bytes32 internal constant BALL_Y_SLOT = bytes32(uint256(11));

    /// @dev `int256 ballVX`, at slot 12. One slot, one partition.
    bytes32 internal constant BALL_VX_SLOT = bytes32(uint256(12));

    /// @dev `int256 ballVY`, at slot 13. One slot, one partition.
    bytes32 internal constant BALL_VY_SLOT = bytes32(uint256(13));

    /// @dev `int256 paddleA`, at slot 14. One slot, one partition.
    bytes32 internal constant PADDLE_A_SLOT = bytes32(uint256(14));

    /// @dev `int256 paddleB`, at slot 15. One slot, one partition.
    bytes32 internal constant PADDLE_B_SLOT = bytes32(uint256(15));

    /// @dev `int256 directionA`, at slot 16. One slot, one partition.
    bytes32 internal constant DIRECTION_A_SLOT = bytes32(uint256(16));

    /// @dev `int256 directionB`, at slot 17. One slot, one partition.
    bytes32 internal constant DIRECTION_B_SLOT = bytes32(uint256(17));

    /// @dev `uint256 gameTime`, at slot 18. One slot, one partition.
    bytes32 internal constant GAME_TIME_SLOT = bytes32(uint256(18));

    /// @dev `uint256 scoreA`, at slot 19. One slot, one partition.
    bytes32 internal constant SCORE_A_SLOT = bytes32(uint256(19));

    /// @dev `uint256 scoreB`, at slot 20. One slot, one partition.
    bytes32 internal constant SCORE_B_SLOT = bytes32(uint256(20));

    /// @dev `uint256 nonceA`, at slot 21. One slot, one partition.
    bytes32 internal constant NONCE_A_SLOT = bytes32(uint256(21));

    /// @dev `uint256 nonceB`, at slot 22. One slot, one partition.
    bytes32 internal constant NONCE_B_SLOT = bytes32(uint256(22));

    /// @dev `mapping(uint256 => bytes32) resultHashes`, at slot 23. The whole mapping is one partition.
    bytes32 internal constant RESULT_HASHES_SLOT = bytes32(uint256(23));

    /// @dev keccak256 over every (variable, slot, type, mode) this file asserts.
    bytes32 internal constant INTERLUDE_LAYOUT =
        0xc965c6f074a01d869e673fddde9df98d007e3e3a45aed6a6a7ef8807ef65a3ce;

    /// @notice Hand the annotated storage over. Call once, from the constructor.
    function _registerInterludeSurface() internal {
        _registerGlobal(Delegated.Bytes32Slot.wrap(MATCH_ID_SLOT));
        _registerGlobal(Delegated.Bytes32Slot.wrap(VERSION_SLOT));
        _registerGlobal(Delegated.Bytes32Slot.wrap(STATUS_SLOT));
        _registerGlobal(Delegated.Bytes32Slot.wrap(PLAYER_A_SLOT));
        _registerGlobal(Delegated.Bytes32Slot.wrap(PLAYER_B_SLOT));
        _registerGlobal(Delegated.Bytes32Slot.wrap(TARGET_PLAYER_SLOT));
        _registerGlobal(Delegated.Bytes32Slot.wrap(WINNER_SLOT));
        _registerGlobal(Delegated.Bytes32Slot.wrap(OPENED_AT_SLOT));
        _registerGlobal(Delegated.Bytes32Slot.wrap(START_BLOCK_SLOT));
        _registerGlobal(Delegated.Bytes32Slot.wrap(SEED_SLOT));
        _registerGlobal(Delegated.Bytes32Slot.wrap(BALL_X_SLOT));
        _registerGlobal(Delegated.Bytes32Slot.wrap(BALL_Y_SLOT));
        _registerGlobal(Delegated.Bytes32Slot.wrap(BALL_VX_SLOT));
        _registerGlobal(Delegated.Bytes32Slot.wrap(BALL_VY_SLOT));
        _registerGlobal(Delegated.Bytes32Slot.wrap(PADDLE_A_SLOT));
        _registerGlobal(Delegated.Bytes32Slot.wrap(PADDLE_B_SLOT));
        _registerGlobal(Delegated.Bytes32Slot.wrap(DIRECTION_A_SLOT));
        _registerGlobal(Delegated.Bytes32Slot.wrap(DIRECTION_B_SLOT));
        _registerGlobal(Delegated.Bytes32Slot.wrap(GAME_TIME_SLOT));
        _registerGlobal(Delegated.Bytes32Slot.wrap(SCORE_A_SLOT));
        _registerGlobal(Delegated.Bytes32Slot.wrap(SCORE_B_SLOT));
        _registerGlobal(Delegated.Bytes32Slot.wrap(NONCE_A_SLOT));
        _registerGlobal(Delegated.Bytes32Slot.wrap(NONCE_B_SLOT));
        _registerGlobalMapping(Delegated.MapUint256Slot.wrap(RESULT_HASHES_SLOT));
    }
}
