import {readFile,writeFile} from "node:fs/promises";
let content="// Generated by npm run abi:v4. Do not edit.\n";
for(const name of ["MarketV4","TournamentsV4"]) {
 const a=JSON.parse(await readFile(`contracts/out/${name}.sol/${name}.json`,"utf8"));
 content+=`export const ${name[0].toLowerCase()+name.slice(1)}Abi = ${JSON.stringify(a.abi)} as const;\n`;
}
await writeFile("shared/abis-v4.ts",content);
