import { readFile, writeFile } from "node:fs/promises";
const names = ["GameV2", "MarketV2", "LMSRV2", "TournamentsV2", "PhysicsV2Harness"];
let content = "// Generated by npm run abi:v2. Do not edit.\n";
for (const name of names) {
  const source = name === "LMSRV2" ? "MarketV2" : name === "PhysicsV2Harness" ? "PhysicsV2" : name;
  const artifact = JSON.parse(await readFile(`contracts/out/${source}.sol/${name}.json`, "utf8"));
  content += `export const ${name[0].toLowerCase() + name.slice(1)}Abi = ${JSON.stringify(artifact.abi)} as const;\n`;
}
await writeFile("shared/abis-v2.ts", content);
