import {readFile,writeFile} from "node:fs/promises";
const artifact=JSON.parse(await readFile("contracts/out/PongInterlude.sol/PongInterlude.json","utf8"));
const hub=JSON.parse(await readFile("node_modules/@interludelayer-sdk/cli/artifacts/InterludeHub.sol/InterludeHub.json","utf8"));
await writeFile("shared/abi-interlude.ts",`// Generated by scripts/abi-interlude.ts from the deployed lab artifact.\nexport const interludeLabAbi = ${JSON.stringify(artifact.abi)} as const;\nexport const interludeHubReadAbi = ${JSON.stringify(hub.abi.filter((x:{type:string;name?:string})=>x.type==="function"&&x.name==="sessionOf"))} as const;\n`);
