import { readFile, writeFile } from "node:fs/promises";
const names = [
  "Game",
  "Vault",
  "Market",
  "LMSR",
  "Tournaments",
  "PhysicsHarness",
] as const;
const sources: Record<string, string> = {
  LMSR: "Market",
  PhysicsHarness: "Physics",
};
let content = "// Generated by npm run abi. Do not edit.\n";
for (const name of names) {
  const artifact = JSON.parse(
    await readFile(
      `contracts/out/${sources[name] || name}.sol/${name}.json`,
      "utf8",
    ),
  );
  content += `export const ${name[0].toLowerCase() + name.slice(1)}Abi = ${JSON.stringify(artifact.abi)} as const;\n`;
}
await writeFile("shared/abis.ts", content);
console.log("Generated six contract ABIs.");
