// A local review artifact, explicitly separate from gameplay and production routes.
import {writeFile,mkdir} from 'node:fs/promises';
import {chaosEvents} from '../shared/chaos-events';
import {chaosIconSvg} from '../shared/chaos-pixels';
const escape=(s:string)=>s.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('"','&quot;');
await mkdir('artifacts/drand',{recursive:true});
const cards=chaosEvents.map(e=>`<article style="--accent:${e.color}"><div class="top"><span class="number">${String(e.id).padStart(2,'0')}</span><span class="rarity">${e.weight===1?'RARE DROP':'CHAOS EVENT'}</span></div><div class="icon">${chaosIconSvg(e.id)}</div><h2>${escape(e.name)}</h2><div class="meta">${e.durationMs/1000} SEC · ${e.target==='player'?'ONE PLAYER':e.target==='both'?'BOTH PLAYERS':'COURT'}</div><p>${escape(e.description)}</p><div class="trail"></div></article>`).join('');
const html=`<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>PONGIT Chaos catalogue study</title><style>
*{box-sizing:border-box}body{margin:0;color:#edf6ff;background:#080c17;font:16px/1.5 system-ui,sans-serif}main{max-width:1420px;margin:auto;padding:56px 32px}.eyebrow{color:#83ebe4;letter-spacing:.15em;font-size:12px}h1{font-size:clamp(32px,5vw,64px);line-height:1.1;margin:12px 0 20px;letter-spacing:-.04em}h1 em{font-style:normal;color:#b995f2}header{border-bottom:1px solid #334058;padding-bottom:28px;margin-bottom:30px}.intro{max-width:760px;color:#aebbd0}.notice{display:inline-block;border:1px solid #66543b;background:#211b13;padding:8px 14px;color:#e7c892;font-size:13px;border-radius:5px}.grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:18px}article{position:relative;overflow:hidden;border:1px solid #344257;border-radius:5px;background:linear-gradient(145deg,#1c2437,#0f1424 65%);padding:18px 20px 22px;box-shadow:inset 0 1px #ffffff08,0 5px 0 #03060d;min-height:285px}.top{display:flex;justify-content:space-between;gap:8px;align-items:center}.number{font-size:11px;color:#bac6d9}.rarity{font-size:9px;letter-spacing:.1em;color:var(--accent)}.icon{width:72px;height:72px;margin:12px 0 16px;padding:6px;background:#0a0f1d;border:1px solid #ffffff0b;box-shadow:0 0 22px color-mix(in srgb,var(--accent),transparent 92%)}svg{width:100%;height:100%;image-rendering:pixelated}h2{font-size:16px;letter-spacing:.04em;margin:0 0 8px}.meta{font-size:10px;color:var(--accent);letter-spacing:.08em}article p{font-size:14px;line-height:1.6;color:#adbcd0;margin-bottom:6px}.trail{position:absolute;height:3px;background:var(--accent);bottom:0;left:20px;right:20px;opacity:.6}footer{margin-top:36px;padding-top:24px;border-top:1px solid #334058;color:#91a3ba;font-size:14px}@media(max-width:1000px){.grid{grid-template-columns:repeat(3,minmax(0,1fr))}}@media(max-width:700px){main{padding:28px 16px}.grid{grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}article{padding:14px;min-height:300px}article p{font-size:14px}h2{font-size:14px}.rarity{font-size:8px}}@media(max-width:400px){.grid{grid-template-columns:1fr}article{min-height:240px}}
</style><main><header><div class="eyebrow">PONGIT / CHAOS / RULES 6 CANDIDATE</div><h1>Expect <em>anything.</em></h1><p class="intro">24 arcade events. Two effect slots. Every rally starts clean.</p><span class="notice">Asset review only. These events are not enabled in the live game.</span></header><div class="grid">${cards}</div><footer>Original pixel artwork. Effects stay inside the arena. The background stays still.<br>Gameplay activation requires hosted randomness, physics, payment and multiplayer qualification.</footer></main></html>`;
await writeFile('artifacts/drand/chaos-catalogue.html',html);console.log('artifacts/drand/chaos-catalogue.html');
