// Real Web Audio output from production cue synthesis, without wallet/network code.
import assert from 'node:assert/strict';
import {build} from 'esbuild';
import {chromium} from '@playwright/test';
import {writeFile} from 'node:fs/promises';
const bundle=await build({stdin:{contents:`import {ArcadeAudio} from './web/lib/audio';window.cues=new ArcadeAudio();document.querySelector('button').onclick=()=>{window.cues.configure({enabled:true,music:0,effects:.6});void window.cues.activate();};`,resolveDir:process.cwd(),loader:'ts'},bundle:true,write:false,platform:'browser',format:'iife'});
const browser=await chromium.launch({headless:true,args:['--no-sandbox'],...(process.env.BROWSER_CHANNEL?{channel:process.env.BROWSER_CHANNEL}:{})});
const report:any={at:new Date().toISOString(),browser:browser.version(),scope:'Real AudioContext analyser signal; does not prove human speaker output',cues:[]};
try{const page=await browser.newPage();await page.route('https://pongit.xyz/**',async route=>{const u=new URL(route.request().url());if(u.pathname==='/audio-check')return route.fulfill({contentType:'text/html',body:'<button>Enable sound</button>'});return route.fulfill({response:await route.fetch({url:'http://countdown-web:3000'+u.pathname})});});await page.goto('https://pongit.xyz/audio-check');await page.addScriptTag({content:bundle.outputFiles[0].text});await page.getByRole('button').click();await page.waitForFunction(()=> (window as any).cues.context?.state==='running');
 for(let id=1;id<=24;id++){const result=await page.evaluate(async id=>{const a=(window as any).cues;a.playChaos(id,'announce',`audio:${id}`);const count=a.diagnostics().voices;a.playChaos(id,'announce',`audio:${id}`);const deduplicated=a.diagnostics().voices===count;let rms=0,peak=0,maxVoices=0;for(let i=0;i<55;i++){const d=a.diagnostics();rms=Math.max(rms,d.rms);peak=Math.max(peak,d.peak);maxVoices=Math.max(maxVoices,d.voices);await new Promise(r=>setTimeout(r,15));}return{id,rms,peak,maxVoices,deduplicated};},id);assert(result.rms>.001&&result.peak<1&&result.maxVoices<=12&&result.deduplicated);report.cues.push(result);}
 report.mute=await page.evaluate(async()=>{const a=(window as any).cues;a.configure({enabled:false});a.playChaos(1,'announce','muted');await new Promise(r=>setTimeout(r,200));return a.diagnostics();});assert.equal(report.mute.voices,0);assert(report.mute.rms<.0001);
 report.suspension=await page.evaluate(async()=>{const a=(window as any).cues;a.hidden();await new Promise(r=>setTimeout(r,100));return a.diagnostics().state;});assert.equal(report.suspension,'suspended');report.passed=true;
}catch(e){report.passed=false;report.error=(e as Error).message;process.exitCode=1;}finally{await browser.close();await writeFile(`artifacts/drand/audio-${process.env.BROWSER_CHANNEL||'chromium'}.json`,JSON.stringify(report,null,2));console.log(JSON.stringify({passed:report.passed,cues:report.cues.length,error:report.error,browser:report.browser}));}
