import {readFile,writeFile,mkdir,readdir,stat} from "node:fs/promises";
import path from "node:path";
import {unified} from "unified";
import remarkParse from "remark-parse";
import remarkMdx from "remark-mdx";
import remarkGfm from "remark-gfm";
import GithubSlugger from "github-slugger";
import {catalog,groups} from "../web/content/docs/catalog";

const root=path.resolve(import.meta.dirname,".."),content=path.join(root,"web/content/docs");
const check=process.argv.includes("--check"),parser=unified().use(remarkParse).use(remarkMdx).use(remarkGfm);
type Node={type:string;value?:string;url?:string;depth?:number;name?:string;children?:Node[]};
const plain=(n:Node):string=>n.value||n.children?.map(plain).join(n.type==="paragraph"?"":" ")||"";
const generated:any[]=[],search:any[]=[],refs:{slug:string;url:string;image:boolean}[]=[];
const allowedComponents=new Set(["Callout","ContractTable","ArchitectureDiagram"]);
const seen=new Set<string>();
for(const page of catalog){
 if(seen.has(page.slug)||!/^([a-z0-9-]+\/)[a-z0-9-]+$/.test(page.slug))throw Error(`Duplicate/invalid slug ${page.slug}`);seen.add(page.slug);
 const source=await readFile(path.join(content,page.slug+".mdx"),"utf8"),tree=parser.parse(source) as Node,slugger=new GithubSlugger();
 const headings:{id:string;text:string;level:number}[]=[];let section={id:"",title:page.title,text:page.description};const sections=[section];
 function walk(node:Node){
  if(node.type==="mdxjsEsm"||node.type==="mdxFlowExpression"||node.type==="mdxTextExpression")throw Error(`${page.slug}: executable MDX expressions are not needed`);
  if(node.type.startsWith("mdxJsx")&&node.name&&!allowedComponents.has(node.name))throw Error(`${page.slug}: unsupported component ${node.name}`);
  if(node.type==="heading"){
   if(node.depth===1)throw Error(`${page.slug}: the page template owns the H1`);
   const text=plain(node).replace(/\s+/g," ").trim(),id=slugger.slug(text);headings.push({id,text,level:node.depth!});section={id,title:text,text:""};sections.push(section);
  }
  if(["paragraph","table","code"].includes(node.type))section.text+=" "+plain(node).replace(/\s+/g," ").trim();
  if((node.type==="link"||node.type==="image")&&node.url)refs.push({slug:page.slug,url:node.url,image:node.type==="image"});
  node.children?.forEach(walk);
 }
 walk(tree);if(headings.length<2||source.length<650)throw Error(`${page.slug}: incomplete article`);
 generated.push({...page,headings});for(const s of sections)search.push({href:`/docs/${page.slug}${s.id?"#"+s.id:""}`,page:page.title,section:s.id?s.title:"Overview",keywords:page.keywords,text:s.text.trim()});
}
for(const ref of refs){
 if(ref.image){if(!ref.url.startsWith("/docs-assets/"))throw Error(`Use local documentation images: ${ref.url}`);await stat(path.join(root,"web/public",ref.url));continue;}
 if(/^https:\/\//.test(ref.url))continue;
 if(ref.url==="/"||ref.url==="/docs"||ref.url==="/admin")continue;
 if(!ref.url.startsWith("/docs/")&&!ref.url.startsWith("#"))throw Error(`${ref.slug}: unsupported link ${ref.url}`);
 const [target,hash]=ref.url.startsWith("#")?[ref.slug,ref.url.slice(1)]:ref.url.slice(6).split("#");
 const page=generated.find(p=>p.slug===target);if(!page)throw Error(`Missing article: ${ref.url}`);
 if(hash&&!page.headings.some((h:any)=>h.id===decodeURIComponent(hash)))throw Error(`Missing anchor: ${ref.url}`);
}
const files:string[]=[];async function list(dir:string){for(const f of await readdir(dir,{withFileTypes:true})){const p=path.join(dir,f.name);if(f.isDirectory())await list(p);else if(f.name.endsWith(".mdx"))files.push(path.relative(content,p).replaceAll("\\","/").slice(0,-4));}}await list(content);
if(files.some(f=>!seen.has(f)))throw Error("Unlisted MDX content");
const deployment=JSON.parse(await readFile(path.join(root,"deployments/testnet.json"),"utf8"));
const contracts=[];for(let d=deployment;d;d=d.legacy){
 const version=d.version||1;const addresses=[];
 for(const [key,label] of Object.entries({game:"Game",arcade:"Arcade sessions",vault:"Vault",market:"Market",lmsr:"LMSR",tournaments:"Tournaments",eloFormula:"ELO formula"})){
  if(d[key]){if(!/^0x[\da-fA-F]{40}$/.test(d[key]))throw Error("Invalid contract address");addresses.push({name:label,address:d[key]});}
 }
 contracts.push({version,chainId:d.chainId,startBlock:d.startBlock,addresses});
}
async function output(file:string,data:string){const target=path.join(root,file);if(check){if(await readFile(target,"utf8")!==data)throw Error(`Stale generated docs: ${file}`);}else{await mkdir(path.dirname(target),{recursive:true});await writeFile(target,data);}}
await output("web/lib/docs.generated.json",JSON.stringify({groups,pages:generated,contracts},null,2)+"\n");
await output("web/public/search/docs-v1.json",JSON.stringify(search)+"\n");
await output("web/content/docs/registry.generated.ts",`// Generated by scripts/docs-build.ts from the reviewed local article catalog.\n${catalog.map((p,i)=>`import Page${i} from "./${p.slug}.mdx";`).join("\n")}\nexport const articles:Record<string,typeof Page0>={\n${catalog.map((p,i)=>`  "${p.slug}":Page${i},`).join("\n")}\n};\n`);
console.log(`${check?"Checked":"Generated"} ${catalog.length} articles, ${search.length} searchable sections, ${refs.length} links/images and ${contracts.length} deployments.`);
